[connections.snowflake]
account = "ATZZOXQ-LXB41040"
user = "ARTURINTERNAL"
password = "!Bavinck&Junius3?"
role = "ACCOUNTADMIN"
warehouse = "COMPUTE_WH"
database = "FLORADEMO"
schema = "CUSTOMERS"
client_session_keep_alive = true